version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - .:/code
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: docker_django_pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ["./wait-for-postgres.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - postgres
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
